function setCalibrationForIC(ee, calibDir,skip_IDs)
    %% creates the ICME.C calibrated Stimulus Info based on the ICuserInput 
    % input: 
    % ee (anex), 
    % calibDir (str) path to Dir that contains the calibration files from the powermeter
    % skip_IDs (list of str with zeros and ID eg ['0001','0010']) optional input to save time 
    %    if the function has previously been called for this ee

    % check if skip_IDs have been specified
    if nargin <= 2 && ~exist('skip_IDs') 
       skip_IDs=[];
    end

    
    % import the user information about the applied filters
    in_dir_name = fullfile( expProcDataDir(ee.ExperimenterID, ee.ExpID),'ICME',strcat("ICUserInput_", ee.ExpID, ".mat"));
    load(in_dir_name);%loads UT
    
    % check if EXPCONTROL aleady read in calibration files (case for all EK
    % recordings)
    if CalibrationDone==1
        % we still need to open the calibration files to check if we presented
        % impossible stimuli (tend to go to high with Laser2 and then it wants
        % to give 60 mW but actually gives 0, because 100% output is 55 mW
        
        % find all names of .txt calib files (those were generated by labview
        % and are for digital laser
        files=dir(fullfile(gen_dir_name(calibDir), '*.txt'));
        TableVarName={'date','LaserComMode','laserType','SerNr', 'calibArray', 'filter','minValue','maxValue'};
        T_cal=table('size', [1,8], 'VariableTypes', {'string','string', 'string','string', 'cell', 'double','double','double'});
        T_cal.Properties.VariableNames=TableVarName;
        for i = 1:length(files)
            filename = files(i).name; 
            if ~contains(filename,'Analog')
                T_cal.LaserComMode(i)='digital';
                file_desc=split(filename,'_');
                T_cal.date(i)=file_desc{1};
                if length(file_desc)==3
                    if strcmp(file_desc{3},'Attenuation.txt')
                        T_cal.filter(i)=1;
                    elseif strcmp(file_desc{3},'Attenuation15.txt')
                        T_cal.filter(i)=1.5;
                    end
                end
                file_desc2=split(file_desc{2},'-');
                T_cal.laserType(i)=file_desc2{1};
                file_desc3=split(file_desc2{2},'.');
                T_cal.SerNr(i)=file_desc3{1};
                T_cal.calibArray{i}=dlmread(fullfile(gen_dir_name(calibDir),filename));
                T_cal.minValue(i)=min(T_cal.calibArray{i}(:,2));
                T_cal.maxValue(i) = max(T_cal.calibArray{i}(:,2));
            end
        end
    
        % for analog Laser calibration files load the .mat structures
        files=dir(fullfile(gen_dir_name(calibDir), 'CAL_Analog*.mat'));
        for ii=1:length(files)
            filename = files(ii).name; 
            file_info=load(fullfile(gen_dir_name(calibDir),filename));
            T_cal.LaserComMode(end+1)='analog';
            file_info.t.Format='yyyyMMdd';
            T_cal.date(end)=string(file_info.t);
            T_cal.filter(end)=file_info.attenuation;
            T_cal.laserType(end)='OBIS LS';
            if file_info.comID==1
                T_cal.SerNr(end)="151367";
            elseif file_info.comID==2
                T_cal.SerNr(end)="191143";
            elseif file_info.comID==3
                T_cal.SerNr(end)="171435";
            end
            T_cal.calibArray{end}=[file_info.Amplitude_values',file_info.Laser_outputs'];
            T_cal.minValue(end)=min(T_cal.calibArray{end}(:,2));
            T_cal.maxValue(end) = max(T_cal.calibArray{end}(:,2));
        end
    
    
        % assign correct callibration per ICME, using the user OD input
        for ii = 1 : numel(UT.data(:,find(contains(UT.fieldNames,'SeriesID'))))
            % check if experiment has been marked -1 by UserInput
            if UT.data{ii,find(contains(UT.fieldNames,'Use'))}==-1
                continue
            end
            fprintf('filling calibrated values for % s \n',UT.data{ii,find(contains(UT.fieldNames,'SeriesID'))})
            %check if this ICME has already been processed
            ICME_desc=split(UT.data{ii,find(contains(UT.fieldNames,'SeriesID'))},'_');
            if ~isempty(skip_IDs)
                if any(all(skip_IDs==ICME_desc{2},2))
                    continue
                end
            end
            IC = loadIcme(icme(ee,UT.data{ii,find(contains(UT.fieldNames,'SeriesID'))}));
            % since the calibration was already considered during the
            % Experiment, the Stimulus Intensities are the same as the
            % calibration intensities
            IC.C(1).stimlistCal=IC.Stim.stimlist;
            bad_ix=[];
    
            % for Laser stimulations 
            if contains(UT.data{ii,find(contains(UT.fieldNames,'ExpType'))},'OBIS_LS594_PulseTrain')
            % save the calibration array with the ICME object
                ix=find(T_cal.SerNr==UT.data{ii,find(contains(UT.fieldNames,'Laser')& ~contains(UT.fieldNames,'Port'))} & T_cal.filter==str2num(UT.data{ii,find(contains(UT.fieldNames,'Filter'))})& T_cal.LaserComMode=='digital');
                if length(ix)>1 % if multiple calib file sexist in folder take first one
                    ix=ix(1);
                    disp('multiple calibration files found for this recording')
                end
                IC.C.CalibArray=T_cal.calibArray{ix};
                IC.C.minIntensity=T_cal.minValue(ix); 
                IC.C.maxIntensity=T_cal.maxValue(ix);
                % check if any impossible stimuli have been attempted (more
                % than 100 or less then 0 % laser output
                bad_ix=find(IC.C.stimlistCal(:,1)>IC.C.maxIntensity | (IC.C.stimlistCal(:,1)<IC.C.minIntensity & IC.C.stimlistCal(:,1)~=0));
            elseif contains(UT.data{ii,find(contains(UT.fieldNames,'ExpType'))},'OBIS_1Fiber_Masking')
                ix=find(T_cal.SerNr==UT.data{ii,contains(UT.fieldNames,'Laser')& ~contains(UT.fieldNames,'Port'))} & T_cal.filter==str2num(UT.data{ii,find(contains(UT.fieldNames,'Filter'))})& T_cal.LaserComMode=='analog');
                if length(ix)>1
                    ix=ix(1);
                    disp('multiple calibration files found for this recording')
                end
                IC.C.CalibArray=T_cal.calibArray{ix};
                IC.C.minIntensity=T_cal.minValue(ix); 
                IC.C.maxIntensity=T_cal.maxValue(ix);
                % check if any impossible stimuli have been attempted (more
                % than 10 V or less then 0 V NI output
                bad_ix=find(IC.C.stimlistCal(:,2)>IC.C.maxIntensity | ... % pusle1 amp > max
                    (IC.C.stimlistCal(:,2)<IC.C.minIntensity & IC.C.stimlistCal(:,2)~=0) |... % pusle1 amp <min
                    IC.C.stimlistCal(:,4)>IC.C.maxIntensity | ...% pusle2 amp > max
                    (IC.C.stimlistCal(:,4)<IC.C.minIntensity & IC.C.stimlistCal(:,4)~=0)); %pusle2 amp < min
            end
    
            IC.C.impossibleStimuli=bad_ix;
            saveIcme(IC);
            
        end
    
        
     %% Case for JG, need to read in the calibration from his excel sheets
    else

    % get the calibration file
        calibFileName = fullfile(calibDir, strcat("Calibration_", ee.ExpID, ".xlsx"));

        % Get sheet names
        [~,sheet_name]=xlsfinfo(calibFileName);
        
        % preallocate data
        DataCalibFile = struct();
        
        for ii = 1:length(sheet_name) 
            % Read sheet
            sheet = sheet_name{ii};
            temp_data = readtable(calibFileName, 'Sheet', sheet);
            
            % Read experiment, date and data
            DataCalibFile(ii).sheetname = sheet;
            DataCalibFile(ii).experiment = temp_data{1,2};
            DataCalibFile(ii).date = datetime(temp_data{1,4}, 'InputFormat', 'dd.MM.yyyy');
            
            % Adjust table to remove additional data
            temp_data = temp_data(3:end, :);
            x_data=temp_data{:,2};
            y_data= temp_data{:,1};
            idx = isnan(x_data); % make sure empty values are nto included in the fit
            x_data= [x_data(~idx);0];% add 0,0 to be sure the curve goes through there
            y_data= [y_data(~idx);0];     


            DataCalibFile(ii).table = table(y_data, x_data,...
                                  'VariableNames', {'Power_percent', 'Power_mW_OD_0'});

        end

    
        % go through all ICME objects and fill IC.C 
        for ii = 1 : numel(UT.data(:,find(contains(UT.fieldNames,'SeriesID'))))
            % check if experiment has been marked -1 by UserInput
            if UT.data{ii,find(contains(UT.fieldNames,'Use'))}==-1
                continue
            end
            fprintf('filling calibrated values for % s \n',UT.data{ii,find(contains(UT.fieldNames,'SeriesID'))})
            %check if this ICME has already been processed
            ICME_desc=split(UT.data{ii,find(contains(UT.fieldNames,'SeriesID'))},'_');
            if ~isempty(skip_IDs)
                if any(all(skip_IDs==ICME_desc{2},2))
                    continue
                end
            end
            IC = loadIcme(icme(ee,UT.data{ii,find(contains(UT.fieldNames,'SeriesID'))}));
            bad_ix=[]; % to make a list of impossible stimuli eg. higher than max laser power
            % check which kind of ICME we have and correspondingly fill the
            % calibration Stimlist
            % for Laser stimulations 
            if contains(UT.data{ii,find(contains(UT.fieldNames,'ExpType'))},'OBIS')
                OD = str2num(UT.data{ii,find(contains(UT.fieldNames,'Filter'))});
                calib_sheet_ix=find(contains(DataCalibFile.sheetname,'Obis'));
                Power_percent=DataCalibFile(calib_sheet_ix).table.Power_percent;
                Power_mW= DataCalibFile(calib_sheet_ix).table.Power_mW_OD_0;
                % use OD_filter to adapt the power in mW
                if OD==0
                    Power_mW_adapted = Power_mW;
                else
                    Power_mW_adapted = Power_mW*10^(-OD);
                end

                %% make a fit to the data
                            %find polynomial fit and store the coefficients
                degree=5;    
                coeffs= polyfit( Power_percent,Power_mW_adapted, degree);
                used_intensities_percent=IC.Stim.stimlist(:,1);
                used_intensities_mW=polyval(coeffs,used_intensities_percent);
                stimlistCal=IC.Stim.stimlist;
                stimlistCal(:,1)=used_intensities_mW;
                
                
%                 % plot fit
%                 x_fit = linspace(0, 100, 100);
%                 y_fit = polyval(coeffs, x_fit);
%                 figure;  % open new figure window for each sheet
%                 hold on; % keep the same axis for all plots
%                 scatter( Power_percent,Power_mW_adapted);
%                 plot(x_fit, y_fit, 'LineWidth', 2);
%                 legend('Data', 'Fit');
%                 ylabel('Power (mW) OD0');
%                 xlabel('Percent Power (%)');
%                 hold off;

                
                IC.C(1).stimlistCal=stimlistCal;
                IC.C(1).CalibArray=[Power_percent/1000,Power_mW_adapted];
                IC.C(1).minIntensity=min(Power_mW_adapted); 
                IC.C(1).maxIntensity=max(Power_mW_adapted);
                IC.C(1).impossibleStimuli=[];
                % check if any impossible stimuli have been attempted (more
                % than 100 or less then 0 % laser output
            elseif contains(UT.data{ii,find(contains(UT.fieldNames,'ExpType'))},'MX') 
                % for acoustic stimuli no calibration necessary
                IC.C(1).stimlistCal=IC.Stim.stimlist;
                IC.C(1).impossibleStimuli=[];
            end
            saveIcme(IC);
        end
    end

end

   
    
 
